package com.securemessage.backend.model;

import java.util.List;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document(collection = "users")
public class User {
  @Id private String id; // This will be the UUID generated by client or server

  private String username; // UUID string

  private String passwordHash; // Bcrypt hash

  private String email; // Optional (encrypted or hashed if stricter privacy needed, but 'email
  // optionnel pour reset')

  // Signal Protocol Keys
  private byte[] identityKey; // Public Identity Key
  private byte[] signedPreKey; // Public Signed Prekey
  private int signedPreKeyId;
  private byte[] signedPreKeySignature;

  private List<PreKeyRecord> oneTimePreKeys;

  // Helper inner class or separate document for PreKeys
  @Data
  public static class PreKeyRecord {
    private int keyId;
    private byte[] publicKey;
  }
}
