services:
  mongodb:
    image: mongo:latest
    container_name: securemessage-mongo-prod
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data-prod:/data/db
    env_file:
      - .env
    networks:
      - secure-network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    build: ./backend
    container_name: securemessage-backend-prod
    expose:
      - "8080"
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - secure-network

  frontend:
    build:
      context: ./front
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
        - VITE_WS_URL=${VITE_WS_URL}
    container_name: securemessage-frontend-prod
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - backend
    networks:
      - secure-network
    volumes:
      - /etc/nginx/sites-available/secure-mess.fr:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  mongo-data-prod:


networks:
  secure-network:
    driver: bridge
