services:
  mongodb:
    image: mongo:latest
    container_name: securemessage-mongo-prod
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
    networks:
      - secure-network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    build: ./backend
    container_name: securemessage-backend-prod
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - secure-network

  frontend:
    build: ./front
    container_name: securemessage-frontend-prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - secure-network

volumes:
  mongo-data-prod:


networks:
  secure-network:
    driver: bridge
