spring.application.name=secure-message-backend
spring.data.mongodb.uri=${MONGODB_URI:mongodb://admin:6z3GYEdbHRCgjwusRcNCb4HVch9fX%2521e%252AR%2521DGVjkGEyYrGtGa6wgkPj6%2524aF0a%25252ax@localhost:27017/}
spring.data.mongodb.database=securemessage
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
spring.mvc.problem-details.enabled=true
server.forward-headers-strategy=native