spring.application.name=secure-message-backend
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/securemessage}
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
